appId: 636826F8-33EB-4219-9436-AA0E47A41166
appPublisher: 永恒瞬间
appPublisherUrl: https://github.com/yhsj0919/MixMusic
display_name: 纯音乐
create_desktop_icon: true
install_dir_name: MixMusic
#locales:
#  - zh
